services:
  app-server:
    build:
      context: . # folder project
      dockerfile: Dockerfile
    container_name: go-rbtmq
    restart: unless-stopped
    env_file:
      - ./app.env
    environment:
      RABBITMQ_DIAL: ${RABBITMQ_DIAL}
    ports:
      - "8005:8005"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend-queue
  rabbitmq:
    image: rabbitmq:4.3.5-management # ubuntu
    container_name: rabbitmq_cont
    ports: 
      - "127.0.0.1:5672:5672" # port untuk service rabbitmq
      - "127.0.0.1:15672:15672" # port untuk DASHBOARD rabbitmq
    restart: unless-stopped
    env_file:
      - ./app.env ## acuan dari lokas docker-compose
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER} ## nama environment image resmi see Docs
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DIAL: ${RABBITMQ_DIAL}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-queue
configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  
volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local
networks:
  backend-queue:
    driver: bridge